Added script for producing Trello statistics
redhat-cop/ninja-points pull request #1
Opened 2017-12-09 15:49 UTC by sabre1041

Script for producing Trello statistics

Get API key at link provided in readme. Fill in variables in script. Execute

2017-12-12 15:32 UTC, etsauer requested changes
@sabre1041 a few things.

2017-12-12 15:32 UTC, etsauer commented on trello-stats.py
> +#!/usr/bin/env python
script should be executable.

2017-12-12 15:32 UTC, etsauer commented on trello-stats.py
> +            print "   - Board: {0} | Card: {1}".format(cards[card]['board']['name'], cards[card]['name'])
When running the script, I get a few results, but then it fails with the following:
```Traceback (most recent call last):
  File "./trello-stats.py", line 79, in <module>
    print "   - Board: {0} | Card: {1}".format(cards[card]['board']['name'], cards[card]['name'])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 28: ordinal not in range(128)
```

2017-12-12 15:32 UTC, etsauer commented on README.md
> +
Can we include a sample run of the script with some dummy output?

2017-12-13 03:11 UTC, sabre1041 commented
@etsauer addressed comments

2018-01-06 18:55 UTC, sabre1041 commented
@etsauer bump

2018-01-08 14:36 UTC, etsauer approved these changes

2018-01-08 14:37 UTC, merged