Added support to filter issues by labels
redhat-cop/ninja-points pull request #8
Opened 2018-01-18 14:38 UTC by sabre1041

Added support to filter GitHub issues by labels.

Modified how results are returned to support providing a set of comma separated labels through the `--labels` parameter. If no parameter is specified, the _enhancement_ label is automatically applied. To negate a label from being returned, add a `-` to the end of the label name within the argument, such as `bugfix-`

This should fully resolve #5

2018-01-18 16:33 UTC, etsauer requested changes
One thing.

2018-01-18 16:33 UTC, etsauer commented on README.md
> +To filter by labels, the `--labels` parameter can be specified followed by a series of comma separated labels (such as `enhancement,bugfix`). To limit the results containing a label, add a `-` at the
@sabre1041 how do we get unlabelled PRs returned?

2018-01-18 17:17 UTC, sabre1041 commented
@etsauer updated logic. please review

2018-01-19 05:25 UTC, sabre1041 commented
@etsauer refactored label logic yet again. Please review

2018-01-23 04:11 UTC, etsauer approved these changes

2018-01-23 04:11 UTC, merged